// Generated by CoffeeScript 1.7.1
(function(doc) {
  if (!(doc.collection === "patient-records" || doc.collection === "incident")) {
    return;
  }
  return emit([doc.subject, doc.grade, doc.week, doc.day], null);
});
