// Generated by CoffeeScript 1.7.1
var Mmlp;

Mmlp = Mmlp || {};

Mmlp.$db = $.couch.db("mmlp");

Mmlp["enum"] = {
  subjects: {
    1: "English",
    2: "Kiswahili"
  },
  iSubjects: {
    "English": "1",
    "Kiswahili": "2"
  }
};
